/**
 * Centralized Error Codes
 *
 * All error codes used across the application are defined here.
 * These are SCREAMING_SNAKE_CASE strings returned in the `error.code` field
 * of API responses. The frontend uses these to show appropriate UI messages.
 *
 * Convention: <DOMAIN>_<REASON>
 *   - UNAUTHORIZED: auth token missing/invalid
 *   - FORBIDDEN: valid auth but insufficient permissions
 *   - NOT_FOUND: resource doesn't exist
 *   - CONFLICT: duplicate/unique constraint violation
 *   - VALIDATION_ERROR: request body/params failed Zod validation
 *
 * Add new codes as features are built — but never remove existing ones
 * without coordinating with the frontend team.
 */

export const ERROR_CODES = {
  // ─── Generic ────────────────────────────────────────────────────────────
  INTERNAL_ERROR: "INTERNAL_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  CONFLICT: "CONFLICT",
  RATE_LIMITED: "RATE_LIMITED",
  EMAIL_SEND_FAILED: "EMAIL_SEND_FAILED",

  // ─── Auth (Phase 1) ────────────────────────────────────────────────────
  USER_NOT_SYNCED: "USER_NOT_SYNCED", // Clerk JWT valid but user not in our DB yet
  INVALID_WEBHOOK_SIGNATURE: "INVALID_WEBHOOK_SIGNATURE",

  // ─── Workspace (Phase 2) ───────────────────────────────────────────────
  WORKSPACE_NOT_FOUND: "WORKSPACE_NOT_FOUND",
  WORKSPACE_SLUG_TAKEN: "WORKSPACE_SLUG_TAKEN",
  NOT_WORKSPACE_MEMBER: "NOT_WORKSPACE_MEMBER",
  INSUFFICIENT_ROLE: "INSUFFICIENT_ROLE",
  CANNOT_DEMOTE_OWNER: "CANNOT_DEMOTE_OWNER",
  CANNOT_REMOVE_OWNER: "CANNOT_REMOVE_OWNER",

  // ─── Department (Phase 3) ──────────────────────────────────────────────
  DEPARTMENT_NOT_FOUND: "DEPARTMENT_NOT_FOUND",
  DEPARTMENT_NAME_TAKEN: "DEPARTMENT_NAME_TAKEN",
  HEAD_NOT_WORKSPACE_MEMBER: "HEAD_NOT_WORKSPACE_MEMBER",
  MEMBER_ALREADY_IN_DEPARTMENT: "MEMBER_ALREADY_IN_DEPARTMENT",
  MEMBER_NOT_IN_DEPARTMENT: "MEMBER_NOT_IN_DEPARTMENT",
  PRIVATE_DEPARTMENT_FORBIDDEN: "PRIVATE_DEPARTMENT_FORBIDDEN",

  // ─── Team (Phase 3) ────────────────────────────────────────────────────
  TEAM_NOT_FOUND: "TEAM_NOT_FOUND",
  TEAM_NAME_TAKEN: "TEAM_NAME_TAKEN",
  LEAD_NOT_WORKSPACE_MEMBER: "LEAD_NOT_WORKSPACE_MEMBER",
  MEMBER_ALREADY_IN_TEAM: "MEMBER_ALREADY_IN_TEAM",
  MEMBER_NOT_IN_TEAM: "MEMBER_NOT_IN_TEAM",
  PRIVATE_TEAM_FORBIDDEN: "PRIVATE_TEAM_FORBIDDEN",

  // ─── Project (Phase 4) ─────────────────────────────────────────────────
  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  PROJECT_NAME_TAKEN: "PROJECT_NAME_TAKEN",
  PROJECT_SLUG_TAKEN: "PROJECT_SLUG_TAKEN",
  PRIVATE_PROJECT_FORBIDDEN: "PRIVATE_PROJECT_FORBIDDEN",
  TEAM_NOT_IN_WORKSPACE: "TEAM_NOT_IN_WORKSPACE",
  MEMBER_ALREADY_IN_PROJECT: "MEMBER_ALREADY_IN_PROJECT",
  MEMBER_NOT_IN_PROJECT: "MEMBER_NOT_IN_PROJECT",

  // ─── Issue (Phase 5) ───────────────────────────────────────────────────
  ISSUE_NOT_FOUND: "ISSUE_NOT_FOUND",
  INVALID_ASSIGNEE: "INVALID_ASSIGNEE", // assigneeId is not a workspace member
  ASSIGNEE_NOT_WORKSPACE_MEMBER: "ASSIGNEE_NOT_WORKSPACE_MEMBER",
  INVALID_RELATED_ISSUE: "INVALID_RELATED_ISSUE",
  SUBTASK_NOT_FOUND: "SUBTASK_NOT_FOUND",
  PARENT_ISSUE_NOT_FOUND: "PARENT_ISSUE_NOT_FOUND",
  INVALID_PARENT_ISSUE: "INVALID_PARENT_ISSUE",
  ISSUE_CYCLE_DETECTED: "ISSUE_CYCLE_DETECTED",
  DEPENDENCY_ALREADY_EXISTS: "DEPENDENCY_ALREADY_EXISTS",
  DEPENDENCY_NOT_FOUND: "DEPENDENCY_NOT_FOUND",
  WATCHER_NOT_WORKSPACE_MEMBER: "WATCHER_NOT_WORKSPACE_MEMBER",
  WATCHER_ALREADY_EXISTS: "WATCHER_ALREADY_EXISTS",
  WATCHER_NOT_FOUND: "WATCHER_NOT_FOUND",
  INVALID_INTEGRATION_REF: "INVALID_INTEGRATION_REF",
  ATTACHMENT_NOT_FOUND: "ATTACHMENT_NOT_FOUND",
  INVALID_ATTACHMENT_REF: "INVALID_ATTACHMENT_REF",
  ATTACHMENT_TYPE_NOT_ALLOWED: "ATTACHMENT_TYPE_NOT_ALLOWED",
  ATTACHMENT_KEY_WORKSPACE_MISMATCH: "ATTACHMENT_KEY_WORKSPACE_MISMATCH",

  // ─── Comment (Phase 6) ─────────────────────────────────────────────────
  COMMENT_NOT_FOUND: "COMMENT_NOT_FOUND",
  NOT_COMMENT_AUTHOR: "NOT_COMMENT_AUTHOR",

  // ─── Label (Phase 7) ───────────────────────────────────────────────────
  LABEL_NOT_FOUND: "LABEL_NOT_FOUND",
  LABEL_NAME_TAKEN: "LABEL_NAME_TAKEN",
  SELF_RELATION_NOT_ALLOWED: "SELF_RELATION_NOT_ALLOWED",

  // ─── Member (Phase 2) ──────────────────────────────────────────────────
  MEMBER_NOT_FOUND: "MEMBER_NOT_FOUND",
  MEMBER_ALREADY_EXISTS: "MEMBER_ALREADY_EXISTS",
  MEMBER_NOT_WORKSPACE_MEMBER: "MEMBER_NOT_WORKSPACE_MEMBER",

  // ─── Upload (Phase 4) ──────────────────────────────────────────────────
  UPLOAD_TYPE_NOT_ALLOWED: "UPLOAD_TYPE_NOT_ALLOWED",
  UPLOAD_FILE_TOO_LARGE: "UPLOAD_FILE_TOO_LARGE",
} as const;

// Type-safe error code type (union of all values)
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
