/**
 * Centralized Error Codes
 *
 * All error codes used across the application are defined here.
 * These are SCREAMING_SNAKE_CASE strings returned in the `error.code` field
 * of API responses. The frontend uses these to show appropriate UI messages.
 *
 * Convention: <DOMAIN>_<REASON>
 *   - UNAUTHORIZED: auth token missing/invalid
 *   - FORBIDDEN: valid auth but insufficient permissions
 *   - NOT_FOUND: resource doesn't exist
 *   - CONFLICT: duplicate/unique constraint violation
 *   - VALIDATION_ERROR: request body/params failed Zod validation
 *
 * Add new codes as features are built — but never remove existing ones
 * without coordinating with the frontend team.
 */

export const ERROR_CODES = {
  // ─── Generic ────────────────────────────────────────────────────────────
  INTERNAL_ERROR: "INTERNAL_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  CONFLICT: "CONFLICT",
  RATE_LIMITED: "RATE_LIMITED",
  EMAIL_SEND_FAILED: "EMAIL_SEND_FAILED",

  // ─── Auth (Phase 1) ────────────────────────────────────────────────────
  USER_NOT_SYNCED: "USER_NOT_SYNCED", // Clerk JWT valid but user not in our DB yet
  INVALID_WEBHOOK_SIGNATURE: "INVALID_WEBHOOK_SIGNATURE",

  // ─── Workspace (Phase 2) ───────────────────────────────────────────────
  WORKSPACE_NOT_FOUND: "WORKSPACE_NOT_FOUND",
  WORKSPACE_SLUG_TAKEN: "WORKSPACE_SLUG_TAKEN",
  NOT_WORKSPACE_MEMBER: "NOT_WORKSPACE_MEMBER",
  WORKSPACE_PREFIX_TAKEN: "WORKSPACE_PREFIX_TAKEN",
  INVALID_WORKSPACE_STATUSES: "INVALID_WORKSPACE_STATUSES",
  INSUFFICIENT_ROLE: "INSUFFICIENT_ROLE",
  CANNOT_DEMOTE_OWNER: "CANNOT_DEMOTE_OWNER",
  CANNOT_REMOVE_OWNER: "CANNOT_REMOVE_OWNER",

  INVITATION_EXPIRED: "INVITATION_EXPIRED",
  INVITATION_ALREADY_ACCEPTED: "INVITATION_ALREADY_ACCEPTED",
  INVITATION_REVOKED: "INVITATION_REVOKED",
  INVITATION_NOT_FOUND: "INVITATION_NOT_FOUND",
  INVITATION_EMAIL_MISMATCH: "INVITATION_EMAIL_MISMATCH",
  ALREADY_MEMBER: "ALREADY_MEMBER",

  // ─── Department (Phase 3) ──────────────────────────────────────────────
  DEPARTMENT_NOT_FOUND: "DEPARTMENT_NOT_FOUND",
  DEPARTMENT_NAME_TAKEN: "DEPARTMENT_NAME_TAKEN",
  HEAD_NOT_WORKSPACE_MEMBER: "HEAD_NOT_WORKSPACE_MEMBER",
  MEMBER_ALREADY_IN_DEPARTMENT: "MEMBER_ALREADY_IN_DEPARTMENT",
  MEMBER_NOT_IN_DEPARTMENT: "MEMBER_NOT_IN_DEPARTMENT",
  PRIVATE_DEPARTMENT_FORBIDDEN: "PRIVATE_DEPARTMENT_FORBIDDEN",

  // ─── Team (Phase 3) ────────────────────────────────────────────────────
  TEAM_NOT_FOUND: "TEAM_NOT_FOUND",
  TEAM_NAME_TAKEN: "TEAM_NAME_TAKEN",
  LEAD_NOT_WORKSPACE_MEMBER: "LEAD_NOT_WORKSPACE_MEMBER",
  MEMBER_ALREADY_IN_TEAM: "MEMBER_ALREADY_IN_TEAM",
  MEMBER_NOT_IN_TEAM: "MEMBER_NOT_IN_TEAM",
  PRIVATE_TEAM_FORBIDDEN: "PRIVATE_TEAM_FORBIDDEN",

  // ─── Project (Phase 4) ─────────────────────────────────────────────────
  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  PROJECT_NAME_TAKEN: "PROJECT_NAME_TAKEN",
  PROJECT_SLUG_TAKEN: "PROJECT_SLUG_TAKEN",
  PRIVATE_PROJECT_FORBIDDEN: "PRIVATE_PROJECT_FORBIDDEN",
  TEAM_NOT_IN_WORKSPACE: "TEAM_NOT_IN_WORKSPACE",
  MEMBER_ALREADY_IN_PROJECT: "MEMBER_ALREADY_IN_PROJECT",
  MEMBER_NOT_IN_PROJECT: "MEMBER_NOT_IN_PROJECT",

  // ─── Issue (Phase 5) ───────────────────────────────────────────────────
  ISSUE_NOT_FOUND: "ISSUE_NOT_FOUND",
  INVALID_ASSIGNEE: "INVALID_ASSIGNEE", // assigneeId is not a workspace member
  ASSIGNEE_NOT_WORKSPACE_MEMBER: "ASSIGNEE_NOT_WORKSPACE_MEMBER",
  ASSIGNEE_NOT_PROJECT_MEMBER: "ASSIGNEE_NOT_PROJECT_MEMBER",
  INVALID_RELATED_ISSUE: "INVALID_RELATED_ISSUE",
  SUBTASK_NOT_FOUND: "SUBTASK_NOT_FOUND",
  PARENT_ISSUE_NOT_FOUND: "PARENT_ISSUE_NOT_FOUND",
  INVALID_PARENT_ISSUE: "INVALID_PARENT_ISSUE",
  ISSUE_CYCLE_DETECTED: "ISSUE_CYCLE_DETECTED",
  DEPENDENCY_ALREADY_EXISTS: "DEPENDENCY_ALREADY_EXISTS",
  DEPENDENCY_NOT_FOUND: "DEPENDENCY_NOT_FOUND",
  WATCHER_NOT_WORKSPACE_MEMBER: "WATCHER_NOT_WORKSPACE_MEMBER",
  WATCHER_ALREADY_EXISTS: "WATCHER_ALREADY_EXISTS",
  WATCHER_NOT_FOUND: "WATCHER_NOT_FOUND",
  INVALID_INTEGRATION_REF: "INVALID_INTEGRATION_REF",
  ATTACHMENT_NOT_FOUND: "ATTACHMENT_NOT_FOUND",
  INVALID_ATTACHMENT_REF: "INVALID_ATTACHMENT_REF",
  ATTACHMENT_TYPE_NOT_ALLOWED: "ATTACHMENT_TYPE_NOT_ALLOWED",
  ATTACHMENT_KEY_WORKSPACE_MISMATCH: "ATTACHMENT_KEY_WORKSPACE_MISMATCH",
  INVALID_STATUS_TRANSITION: "INVALID_STATUS_TRANSITION",
  STATUS_TRANSITION_FORBIDDEN: "STATUS_TRANSITION_FORBIDDEN",
  STATUS_ENTRY_RULE_FAILED: "STATUS_ENTRY_RULE_FAILED",
  APPROVAL_REQUIREMENTS_NOT_MET: "APPROVAL_REQUIREMENTS_NOT_MET",
  APPROVAL_NOT_REQUIRED: "APPROVAL_NOT_REQUIRED",
  APPROVAL_NOT_ELIGIBLE: "APPROVAL_NOT_ELIGIBLE",
  APPROVAL_NOT_FOUND: "APPROVAL_NOT_FOUND",

  // ─── Comment (Phase 6) ─────────────────────────────────────────────────
  COMMENT_NOT_FOUND: "COMMENT_NOT_FOUND",
  NOT_COMMENT_AUTHOR: "NOT_COMMENT_AUTHOR",
  COMMENT_PARENT_NOT_FOUND: "COMMENT_PARENT_NOT_FOUND",
  COMMENT_PARENT_CROSS_ISSUE: "COMMENT_PARENT_CROSS_ISSUE",
  COMMENT_EDIT_FORBIDDEN: "COMMENT_EDIT_FORBIDDEN",
  COMMENT_DELETE_FORBIDDEN: "COMMENT_DELETE_FORBIDDEN",
  COMMENT_ATTACHMENT_NOT_FOUND: "COMMENT_ATTACHMENT_NOT_FOUND",

  // ─── Label (Phase 7) ───────────────────────────────────────────────────
  LABEL_NOT_FOUND: "LABEL_NOT_FOUND",
  LABEL_NAME_TAKEN: "LABEL_NAME_TAKEN",
  LABEL_ALREADY_EXISTS: "LABEL_ALREADY_EXISTS",
  LABEL_INVALID_COLOR: "LABEL_INVALID_COLOR",
  LABEL_NAME_INVALID: "LABEL_NAME_INVALID",
  LABEL_LIMIT_REACHED: "LABEL_LIMIT_REACHED",
  ISSUE_LABEL_LIMIT_REACHED: "ISSUE_LABEL_LIMIT_REACHED",
  SELF_RELATION_NOT_ALLOWED: "SELF_RELATION_NOT_ALLOWED",

  // ─── Member (Phase 2) ──────────────────────────────────────────────────
  MEMBER_NOT_FOUND: "MEMBER_NOT_FOUND",
  MEMBER_ALREADY_EXISTS: "MEMBER_ALREADY_EXISTS",
  MEMBER_NOT_WORKSPACE_MEMBER: "MEMBER_NOT_WORKSPACE_MEMBER",

  // ─── Upload (Phase 4) ──────────────────────────────────────────────────
  UPLOAD_TYPE_NOT_ALLOWED: "UPLOAD_TYPE_NOT_ALLOWED",
  UPLOAD_FILE_TOO_LARGE: "UPLOAD_FILE_TOO_LARGE",

  // ─── Cycle (Phase 11) ──────────────────────────────────────────────────
  CYCLE_NOT_FOUND: "CYCLE_NOT_FOUND",
  CYCLE_DATE_INVALID: "CYCLE_DATE_INVALID",
  CYCLE_OVERLAP_NOT_ALLOWED: "CYCLE_OVERLAP_NOT_ALLOWED",
  CYCLE_CURRENT_ALREADY_EXISTS: "CYCLE_CURRENT_ALREADY_EXISTS",
  CYCLE_COMPLETED_IMMUTABLE: "CYCLE_COMPLETED_IMMUTABLE",
  CYCLE_TEAM_MISMATCH: "CYCLE_TEAM_MISMATCH",
  CYCLE_ASSIGN_COMPLETED_FORBIDDEN: "CYCLE_ASSIGN_COMPLETED_FORBIDDEN",
  CYCLE_REOPEN_FORBIDDEN: "CYCLE_REOPEN_FORBIDDEN",

  // ─── Template (Phase 12) ───────────────────────────────────────────────
  TEMPLATE_NOT_FOUND: "TEMPLATE_NOT_FOUND",
  TEMPLATE_ALREADY_ACTIVE: "TEMPLATE_ALREADY_ACTIVE",
  TEMPLATE_ACTIVATION_CONFLICT: "TEMPLATE_ACTIVATION_CONFLICT",
  TEMPLATE_DEFAULT_CONFLICT: "TEMPLATE_DEFAULT_CONFLICT",
  TEMPLATE_NAME_TAKEN: "TEMPLATE_NAME_TAKEN",
  TEMPLATE_VALIDATION_FAILED: "TEMPLATE_VALIDATION_FAILED",

  // ─── Roadmap (Phase 15) ────────────────────────────────────────────────
  ROADMAP_DISABLED_FOR_PROJECT: "ROADMAP_DISABLED_FOR_PROJECT",
  ROADMAP_INVALID_DATE_RANGE: "ROADMAP_INVALID_DATE_RANGE",
  ROADMAP_SCHEDULE_CONFLICT: "ROADMAP_SCHEDULE_CONFLICT",
  ROADMAP_MILESTONE_NOT_FOUND: "ROADMAP_MILESTONE_NOT_FOUND",
  ROADMAP_DEPENDENCY_DUPLICATE: "ROADMAP_DEPENDENCY_DUPLICATE",
  ROADMAP_DEPENDENCY_CYCLE: "ROADMAP_DEPENDENCY_CYCLE",
  ROADMAP_DEPENDENCY_CANCELLED: "ROADMAP_DEPENDENCY_CANCELLED",
  ROADMAP_DEPENDENCY_INVALID_SCOPE: "ROADMAP_DEPENDENCY_INVALID_SCOPE",
  ROADMAP_FORBIDDEN: "ROADMAP_FORBIDDEN",

  // ─── Documents (Phase 16) ───────────────────────────────────────────────
  DOCUMENT_NOT_FOUND: "DOCUMENT_NOT_FOUND",
  DOCUMENT_TYPE_NOT_ALLOWED: "DOCUMENT_TYPE_NOT_ALLOWED",
  DOCUMENT_KEY_WORKSPACE_MISMATCH: "DOCUMENT_KEY_WORKSPACE_MISMATCH",
  DOCUMENT_SCOPE_INVALID: "DOCUMENT_SCOPE_INVALID",
  DOCUMENT_UPLOAD_FORBIDDEN: "DOCUMENT_UPLOAD_FORBIDDEN",
  FOLDER_NOT_FOUND: "FOLDER_NOT_FOUND",
  FOLDER_NAME_CONFLICT: "FOLDER_NAME_CONFLICT",

  // ─── API Key (Phase 18) ─────────────────────────────────────────────
  INVALID_API_KEY: "INVALID_API_KEY",
  API_KEY_EXPIRED: "API_KEY_EXPIRED",
  API_KEY_REVOKED: "API_KEY_REVOKED",
  API_KEY_NOT_FOUND: "API_KEY_NOT_FOUND",
  API_KEY_LIMIT_REACHED: "API_KEY_LIMIT_REACHED",

  // ─── Integration (Phase 19) ─────────────────────────────────────────
  INTEGRATION_NOT_FOUND: "INTEGRATION_NOT_FOUND",
  INTEGRATION_ALREADY_CONNECTED: "INTEGRATION_ALREADY_CONNECTED",
  INTEGRATION_NOT_CONNECTED: "INTEGRATION_NOT_CONNECTED",
  INTEGRATION_PROVIDER_INVALID: "INTEGRATION_PROVIDER_INVALID",
  GITHUB_NOT_CONFIGURED: "GITHUB_NOT_CONFIGURED",
  GITHUB_OAUTH_FAILED: "GITHUB_OAUTH_FAILED",
  GITHUB_WEBHOOK_SIGNATURE_INVALID: "GITHUB_WEBHOOK_SIGNATURE_INVALID",
  SLACK_NOT_CONFIGURED: "SLACK_NOT_CONFIGURED",
  SLACK_OAUTH_FAILED: "SLACK_OAUTH_FAILED",
  SLACK_SIGNATURE_INVALID: "SLACK_SIGNATURE_INVALID",
  DRIVE_NOT_CONFIGURED: "DRIVE_NOT_CONFIGURED",
  DRIVE_NOT_CONNECTED: "DRIVE_NOT_CONNECTED",
  DRIVE_ALREADY_CONNECTED: "DRIVE_ALREADY_CONNECTED",
  DRIVE_OAUTH_FAILED: "DRIVE_OAUTH_FAILED",
  DRIVE_TOKEN_REFRESH_FAILED: "DRIVE_TOKEN_REFRESH_FAILED",
  DRIVE_UPLOAD_SESSION_FAILED: "DRIVE_UPLOAD_SESSION_FAILED",
  DRIVE_TOKEN_CORRUPTED: "DRIVE_TOKEN_CORRUPTED",

  // ─── Billing (Phase 13) ────────────────────────────────────────────────
  BILLING_INVALID_PLAN: "BILLING_INVALID_PLAN",
  BILLING_ALREADY_ON_PLAN: "BILLING_ALREADY_ON_PLAN",
  BILLING_NO_DEFAULT_PAYMENT_METHOD: "BILLING_NO_DEFAULT_PAYMENT_METHOD",
  BILLING_PAYMENT_METHOD_INVALID: "BILLING_PAYMENT_METHOD_INVALID",
  SUBSCRIPTION_NOT_FOUND: "SUBSCRIPTION_NOT_FOUND",
  FREE_PLAN_MEMBER_LIMIT_REACHED: "FREE_PLAN_MEMBER_LIMIT_REACHED",
  FREE_PLAN_ACCESS_LIMIT_EXCEEDED: "FREE_PLAN_ACCESS_LIMIT_EXCEEDED",
  FREE_PLAN_TEAM_LIMIT_REACHED: "FREE_PLAN_TEAM_LIMIT_REACHED",
  INTEGRATION_PLAN_UPGRADE_REQUIRED: "INTEGRATION_PLAN_UPGRADE_REQUIRED",
  PAYMENT_METHOD_NOT_FOUND: "PAYMENT_METHOD_NOT_FOUND",
  PAYMENT_METHOD_IN_USE: "PAYMENT_METHOD_IN_USE",
  STRIPE_CUSTOMER_MISSING: "STRIPE_CUSTOMER_MISSING",
  STRIPE_SUBSCRIPTION_MISSING: "STRIPE_SUBSCRIPTION_MISSING",
  STRIPE_WEBHOOK_INVALID_SIGNATURE: "STRIPE_WEBHOOK_INVALID_SIGNATURE",
  BILLING_UNKNOWN_PRICE_ID: "BILLING_UNKNOWN_PRICE_ID",
  STORAGE_LIMIT_EXCEEDED: "STORAGE_LIMIT_EXCEEDED",

  // ─── AI (Phase 20) ──────────────────────────────────────────────
  AI_NOT_CONFIGURED: "AI_NOT_CONFIGURED",
  AI_PROVIDER_ERROR: "AI_PROVIDER_ERROR",
  AI_RESPONSE_INVALID: "AI_RESPONSE_INVALID",
  AI_BUDGET_EXCEEDED: "AI_BUDGET_EXCEEDED",
  AI_RATE_LIMITED: "AI_RATE_LIMITED",
  AI_FEATURE_DISABLED: "AI_FEATURE_DISABLED",
  AI_PLAN_UPGRADE_REQUIRED: "AI_PLAN_UPGRADE_REQUIRED",
  AI_SUGGESTION_NOT_FOUND: "AI_SUGGESTION_NOT_FOUND",
  AI_SUGGESTION_NOT_OPEN: "AI_SUGGESTION_NOT_OPEN",
  AI_QUEUE_UNAVAILABLE: "AI_QUEUE_UNAVAILABLE",
  AI_CONNECTION_AUTH_UNSUPPORTED: "AI_CONNECTION_AUTH_UNSUPPORTED",
  AI_CONNECTION_AUTH_NOT_IMPLEMENTED: "AI_CONNECTION_AUTH_NOT_IMPLEMENTED",
  AI_CONNECTION_CLIENT_UNSUPPORTED: "AI_CONNECTION_CLIENT_UNSUPPORTED",
  AI_CONNECTION_NOT_FOUND: "AI_CONNECTION_NOT_FOUND",
  AI_CONNECTION_REVOKED: "AI_CONNECTION_REVOKED",
  AI_CONNECTION_EXPIRED: "AI_CONNECTION_EXPIRED",

  // ─── Scopes (Phase 21) ─────────────────────────────────────────────────
  INSUFFICIENT_SCOPE: "INSUFFICIENT_SCOPE",
} as const;

// Type-safe error code type (union of all values)
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
