-- ActivityType enum expansion for Phase 8
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'ISSUE_TYPE_CHANGED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'ISSUE_STATUS_CHANGED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'ISSUE_PRIORITY_CHANGED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'ISSUE_ASSIGNEE_CHANGED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'ISSUE_DUE_DATE_CHANGED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'ISSUE_SCOPE_CHANGED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'ISSUE_ARCHIVED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'COMMENT_CREATED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'COMMENT_EDITED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'COMMENT_DELETED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'COMMENT_MENTIONED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'PROJECT_CREATED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'PROJECT_UPDATED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'PROJECT_MEMBER_ADDED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'PROJECT_MEMBER_REMOVED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'TEAM_MEMBER_JOINED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'TEAM_MEMBER_REMOVED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'TEAM_MEMBER_ROLE_CHANGED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'WORKSPACE_MEMBER_JOINED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'WORKSPACE_MEMBER_REMOVED';

-- ActivityTargetType enum expansion
ALTER TYPE "ActivityTargetType" ADD VALUE IF NOT EXISTS 'WORKSPACE';
ALTER TYPE "ActivityTargetType" ADD VALUE IF NOT EXISTS 'COMMENT';
ALTER TYPE "ActivityTargetType" ADD VALUE IF NOT EXISTS 'LABEL';
ALTER TYPE "ActivityTargetType" ADD VALUE IF NOT EXISTS 'MEMBER';
