/*
  Warnings:

  - The values [ISSUE_CYCLE_ASSIGNED,ISSUE_CYCLE_REMOVED] on the enum `ActivityType` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "ActivityType_new" AS ENUM ('ISSUE_CREATED', 'ISSUE_COMPLETED', 'COMMENT_ADDED', 'MEMBER_JOINED', 'STATUS_CHANGED', 'ASSIGNMENT_CHANGED', 'LABEL_CREATED', 'LABEL_UPDATED', 'LABEL_DELETED', 'ISSUE_LABEL_ADDED', 'ISSUE_LABEL_REMOVED', 'ISSUE_TYPE_CHANGED', 'ISSUE_STATUS_CHANGED', 'ISSUE_PRIORITY_CHANGED', 'ISSUE_ASSIGNEE_CHANGED', 'ISSUE_DUE_DATE_CHANGED', 'ISSUE_SCOPE_CHANGED', 'ISSUE_ARCHIVED', 'COMMENT_CREATED', 'COMMENT_EDITED', 'COMMENT_DELETED', 'COMMENT_MENTIONED', 'PROJECT_CREATED', 'PROJECT_UPDATED', 'PROJECT_MEMBER_ADDED', 'PROJECT_MEMBER_REMOVED', 'TEAM_MEMBER_JOINED', 'TEAM_MEMBER_REMOVED', 'TEAM_MEMBER_ROLE_CHANGED', 'WORKSPACE_MEMBER_JOINED', 'WORKSPACE_MEMBER_REMOVED', 'CYCLE_CREATED', 'CYCLE_UPDATED', 'CYCLE_DATES_CHANGED', 'CYCLE_GOAL_CHANGED', 'CYCLE_STARTED', 'CYCLE_COMPLETED', 'CYCLE_REOPENED', 'CYCLE_DELETED', 'ISSUE_CYCLE_CHANGED', 'ISSUE_ADDED_TO_CYCLE', 'ISSUE_REMOVED_FROM_CYCLE', 'CYCLE_ISSUE_STATUS_CHANGED', 'CYCLE_ISSUE_PRIORITY_CHANGED', 'CYCLE_ISSUE_ASSIGNEE_CHANGED', 'CYCLE_ISSUE_COMMENT_CREATED', 'CYCLE_CARRY_OVER', 'TEMPLATE_CREATED', 'TEMPLATE_UPDATED', 'TEMPLATE_DELETED', 'TEMPLATE_ACTIVATED', 'TEMPLATE_DEACTIVATED', 'TEMPLATE_APPLIED');
ALTER TABLE "Activity" ALTER COLUMN "type" TYPE "ActivityType_new" USING ("type"::text::"ActivityType_new");
ALTER TYPE "ActivityType" RENAME TO "ActivityType_old";
ALTER TYPE "ActivityType_new" RENAME TO "ActivityType";
DROP TYPE "public"."ActivityType_old";
COMMIT;

-- DropForeignKey
ALTER TABLE "Cycle" DROP CONSTRAINT "Cycle_teamId_fkey";

-- DropForeignKey
ALTER TABLE "Notification" DROP CONSTRAINT "Notification_actorId_fkey";

-- DropIndex
DROP INDEX "Activity_workspaceId_metadata_idx";

-- DropIndex
DROP INDEX "Subscription_workspaceId_idx";

-- DropIndex
DROP INDEX "Template_workspaceId_idx";

-- AlterTable
ALTER TABLE "Cycle" ALTER COLUMN "startsAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "endsAt" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "PaymentMethod" ALTER COLUMN "updatedAt" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Template" ALTER COLUMN "defaultLabelIds" DROP DEFAULT,
ALTER COLUMN "categoryOptions" DROP DEFAULT,
ALTER COLUMN "priorityOptions" DROP DEFAULT,
ALTER COLUMN "statusOptions" DROP DEFAULT,
ALTER COLUMN "labelOptions" DROP DEFAULT,
ALTER COLUMN "checklistItems" DROP DEFAULT;

-- AlterTable
ALTER TABLE "TemplateApplication" ALTER COLUMN "updatedAt" DROP DEFAULT;

-- CreateIndex
CREATE INDEX "Notification_workspaceId_idx" ON "Notification"("workspaceId");

-- RenameForeignKey
ALTER TABLE "Notification" RENAME CONSTRAINT "Notification_userId_fkey" TO "Notification_recipientUserId_fkey";

-- AddForeignKey
ALTER TABLE "Cycle" ADD CONSTRAINT "Cycle_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "Team"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_actorUserId_fkey" FOREIGN KEY ("actorUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
