import { prisma } from "./prisma.js";

type ActivityTargetType =
  | "ISSUE"
  | "PROJECT"
  | "TEAM"
  | "DEPARTMENT"
  | "WORKSPACE"
  | "COMMENT"
  | "LABEL"
  | "MEMBER"
  | "CYCLE"
  | "TEMPLATE"
  | "DOCUMENT"
  | "INTEGRATION";

type ActivityType =
  | "ISSUE_CREATED"
  | "ISSUE_COMPLETED"
  | "COMMENT_ADDED"
  | "MEMBER_JOINED"
  | "STATUS_CHANGED"
  | "ASSIGNMENT_CHANGED"
  | "LABEL_CREATED"
  | "LABEL_UPDATED"
  | "LABEL_DELETED"
  | "ISSUE_LABEL_ADDED"
  | "ISSUE_LABEL_REMOVED"
  | "ISSUE_TYPE_CHANGED"
  | "ISSUE_STATUS_CHANGED"
  | "ISSUE_PRIORITY_CHANGED"
  | "ISSUE_ASSIGNEE_CHANGED"
  | "ISSUE_DUE_DATE_CHANGED"
  | "ISSUE_SCOPE_CHANGED"
  | "ISSUE_ARCHIVED"
  | "COMMENT_CREATED"
  | "COMMENT_EDITED"
  | "COMMENT_DELETED"
  | "COMMENT_MENTIONED"
  | "PROJECT_CREATED"
  | "PROJECT_UPDATED"
  | "PROJECT_MEMBER_ADDED"
  | "PROJECT_MEMBER_REMOVED"
  | "TEAM_MEMBER_JOINED"
  | "TEAM_MEMBER_REMOVED"
  | "TEAM_MEMBER_ROLE_CHANGED"
  | "WORKSPACE_MEMBER_JOINED"
  | "WORKSPACE_MEMBER_REMOVED"
  | "CYCLE_CREATED"
  | "CYCLE_UPDATED"
  | "CYCLE_DATES_CHANGED"
  | "CYCLE_GOAL_CHANGED"
  | "CYCLE_STARTED"
  | "CYCLE_COMPLETED"
  | "CYCLE_REOPENED"
  | "CYCLE_DELETED"
  | "ISSUE_CYCLE_CHANGED"
  | "ISSUE_ADDED_TO_CYCLE"
  | "ISSUE_REMOVED_FROM_CYCLE"
  | "CYCLE_ISSUE_STATUS_CHANGED"
  | "CYCLE_ISSUE_PRIORITY_CHANGED"
  | "CYCLE_ISSUE_ASSIGNEE_CHANGED"
  | "CYCLE_ISSUE_COMMENT_CREATED"
  | "CYCLE_CARRY_OVER"
  | "TEMPLATE_CREATED"
  | "TEMPLATE_UPDATED"
  | "TEMPLATE_DELETED"
  | "TEMPLATE_ACTIVATED"
  | "TEMPLATE_DEACTIVATED"
  | "TEMPLATE_APPLIED"
  | "ROADMAP_SCHEDULE_UPDATED"
  | "ROADMAP_MILESTONE_CREATED"
  | "ROADMAP_MILESTONE_UPDATED"
  | "ROADMAP_MILESTONE_COMPLETED"
  | "ROADMAP_MILESTONE_DELETED"
  | "ROADMAP_MILESTONES_REORDERED"
  | "ROADMAP_DEPENDENCY_CREATED"
  | "ROADMAP_DEPENDENCY_RESOLVED"
  | "ROADMAP_DEPENDENCY_CANCELLED"
  | "ROADMAP_DEPENDENCY_DELETED"
  | "DOCUMENT_CREATED"
  | "DOCUMENT_UPDATED"
  | "DOCUMENT_DELETED"
  | "API_KEY_CREATED"
  | "API_KEY_REVOKED"
  | "INTEGRATION_CONNECTED"
  | "INTEGRATION_DISCONNECTED"
  | "GITHUB_COMMIT_LINKED"
  | "GITHUB_BRANCH_LINKED"
  | "GITHUB_PR_OPENED"
  | "GITHUB_PR_MERGED"
  | "GITHUB_PR_CLOSED"
  | "GITHUB_PR_REVIEW";

interface LogActivityInput {
  workspaceId: string;
  actorId: string;
  type: ActivityType;
  targetType: ActivityTargetType;
  targetId: string;
  message: string;
  metadata?: Record<string, unknown>;
}

export async function logActivity(input: LogActivityInput) {
  await prisma.activity.create({
    data: {
      workspaceId: input.workspaceId,
      actorId: input.actorId,
      type: input.type as any,
      targetType: input.targetType as any,
      targetId: input.targetId,
      description: input.message,
      metadata: input.metadata ?? null,
    } as any,
  });
}
