ALTER TYPE "AiSuggestionType" ADD VALUE IF NOT EXISTS 'PROJECT_HEALTH';
ALTER TYPE "AiSuggestionType" ADD VALUE IF NOT EXISTS 'TEAM_HEALTH';
ALTER TYPE "AiSuggestionType" ADD VALUE IF NOT EXISTS 'CYCLE_HEALTH';
