-- Phase 11 activity contract extensions for cycles

ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'CYCLE_DATES_CHANGED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'CYCLE_GOAL_CHANGED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'CYCLE_STARTED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'ISSUE_CYCLE_CHANGED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'ISSUE_ADDED_TO_CYCLE';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'ISSUE_REMOVED_FROM_CYCLE';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'CYCLE_ISSUE_STATUS_CHANGED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'CYCLE_ISSUE_PRIORITY_CHANGED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'CYCLE_ISSUE_ASSIGNEE_CHANGED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'CYCLE_ISSUE_COMMENT_CREATED';

CREATE INDEX IF NOT EXISTS "Activity_workspaceId_metadata_idx"
  ON "Activity"("workspaceId", "metadata");
