-- Phase 19: GitHub Integration — Add activity types for integration events

ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'INTEGRATION_CONNECTED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'INTEGRATION_DISCONNECTED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'GITHUB_COMMIT_LINKED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'GITHUB_BRANCH_LINKED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'GITHUB_PR_OPENED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'GITHUB_PR_MERGED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'GITHUB_PR_CLOSED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'GITHUB_PR_REVIEW';
